apiVersion: v1
kind: Service
metadata:
  name: attache-service
  namespace: test
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: attache-server
  type: NodePort  
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 32000

